"""
Setup Wizard API

Endpoints for first-run configuration of Gatekeeper.
Handles service validation, config persistence, and initial admin user creation.
"""

import logging
import os
import secrets

from flask import Blueprint, jsonify, request

from gatekeeper.models import db, User

logger = logging.getLogger(__name__)

setup_bp = Blueprint('setup', __name__, url_prefix='/api/setup')

# Path where persistent .env is written (Docker volume)
ENV_FILE_PATH = os.getenv('GATEKEEPER_ENV_PATH', '/app/data/.env')


def setup_needed() -> bool:
    """Check if first-run setup is needed (no users in DB)."""
    try:
        return User.query.count() == 0
    except Exception:
        return True


@setup_bp.route('/status', methods=['GET'])
def status():
    """Return whether setup wizard should be shown."""
    needs_setup = setup_needed()
    return jsonify({
        'setup_needed': needs_setup,
        'has_users': not needs_setup,
        'env_file_exists': os.path.isfile(ENV_FILE_PATH),
    })


@setup_bp.route('/validate', methods=['POST'])
def validate():
    """
    Validate service connections with provided credentials.

    Accepts JSON with the service to test and its configuration.
    """
    data = request.get_json() or {}
    service = data.get('service')
    results = {}

    if service == 'jellyseerr' or service == 'all':
        results['jellyseerr'] = _test_jellyseerr(
            data.get('jellyseerr_url', ''),
            data.get('jellyseerr_api_key', ''),
        )

    if service == 'radarr' or service == 'all':
        results['radarr'] = _test_radarr(
            data.get('radarr_url', ''),
            data.get('radarr_api_key', ''),
        )

    if service == 'sonarr' or service == 'all':
        results['sonarr'] = _test_sonarr(
            data.get('sonarr_url', ''),
            data.get('sonarr_api_key', ''),
        )

    if service == 'tmdb' or service == 'all':
        results['tmdb'] = _test_tmdb(data.get('tmdb_api_key', ''))

    if service == 'ai' or service == 'all':
        results['ai'] = _test_ai(
            data.get('ai_provider', 'claude'),
            data.get('ai_api_key', ''),
            data.get('ai_base_url', ''),
            data.get('ai_model', ''),
        )

    if service == 'mattermost':
        results['mattermost'] = _test_webhook(
            data.get('mattermost_webhook', ''), 'Mattermost'
        )

    if service == 'discord':
        results['discord'] = _test_webhook(
            data.get('discord_webhook', ''), 'Discord'
        )

    return jsonify(results)


@setup_bp.route('/jellyseerr-users', methods=['POST'])
def jellyseerr_users():
    """Fetch user list from Jellyseerr for admin user selection."""
    data = request.get_json() or {}
    url = data.get('jellyseerr_url', '')
    api_key = data.get('jellyseerr_api_key', '')

    if not url or not api_key:
        return jsonify({'error': 'Jellyseerr URL and API key required'}), 400

    try:
        from gatekeeper.services.jellyseerr import JellyseerrClient
        client = JellyseerrClient(url=url, api_key=api_key)
        users = client.get_all_users()
        return jsonify({
            'users': [
                {
                    'id': u.id,
                    'username': u.username or u.email,
                    'email': u.email,
                    'display_name': u.display_name,
                    'is_admin': u.is_admin,
                }
                for u in users
            ]
        })
    except Exception as e:
        logger.error(f"Failed to fetch Jellyseerr users: {e}")
        return jsonify({'error': str(e)}), 500


@setup_bp.route('/complete', methods=['POST'])
def complete():
    """
    Save configuration and create the initial admin user.

    Expects JSON with all config values and admin user info.
    """
    if not setup_needed():
        return jsonify({'error': 'Setup already completed'}), 400

    data = request.get_json() or {}

    # Build .env content
    env_lines = [
        '# Gatekeeper configuration - generated by setup wizard',
        f'GATEKEEPER_SECRET_KEY={secrets.token_hex(32)}',
        f'GATEKEEPER_URL={data.get("external_url", "http://localhost:5000")}',
        '',
        '# Jellyseerr',
        f'JELLYSEERR_URL={data.get("jellyseerr_url", "")}',
        f'JELLYSEERR_API_KEY={data.get("jellyseerr_api_key", "")}',
        '',
        '# Radarr',
        f'RADARR_URL={data.get("radarr_url", "")}',
        f'RADARR_API_KEY={data.get("radarr_api_key", "")}',
        '',
        '# Sonarr',
        f'SONARR_URL={data.get("sonarr_url", "")}',
        f'SONARR_API_KEY={data.get("sonarr_api_key", "")}',
        '',
        '# TMDB',
        f'TMDB_API_KEY={data.get("tmdb_api_key", "")}',
        '',
        '# AI Provider',
        f'AI_PROVIDER={data.get("ai_provider", "claude")}',
        f'AI_API_KEY={data.get("ai_api_key", "")}',
    ]

    if data.get('ai_base_url'):
        env_lines.append(f'AI_BASE_URL={data["ai_base_url"]}')
    if data.get('ai_model'):
        env_lines.append(f'AI_MODEL={data["ai_model"]}')

    env_lines.append('')
    env_lines.append('# Notifications')

    if data.get('mattermost_webhook'):
        env_lines.append(f'MATTERMOST_WEBHOOK={data["mattermost_webhook"]}')
    if data.get('discord_webhook'):
        env_lines.append(f'DISCORD_WEBHOOK={data["discord_webhook"]}')

    env_lines.append('')

    # Write .env file
    try:
        os.makedirs(os.path.dirname(ENV_FILE_PATH), exist_ok=True)
        with open(ENV_FILE_PATH, 'w') as f:
            f.write('\n'.join(env_lines) + '\n')
        logger.info(f"Configuration written to {ENV_FILE_PATH}")
    except Exception as e:
        logger.error(f"Failed to write .env file: {e}")
        return jsonify({'error': f'Failed to write config: {e}'}), 500

    # Set env vars in current process so they take effect immediately
    _apply_env_vars(data)

    # Create admin user
    admin_username = data.get('admin_username', '').strip()
    if not admin_username:
        return jsonify({'error': 'Admin username is required'}), 400

    try:
        user = User(
            username=admin_username,
            user_type='admin',
            jellyseerr_username=data.get('jellyseerr_username') or admin_username,
            jellyseerr_id=data.get('jellyseerr_id'),
            display_name=data.get('admin_display_name') or admin_username,
            email=data.get('admin_email'),
        )
        db.session.add(user)
        db.session.commit()
        logger.info(f"Admin user '{admin_username}' created")
    except Exception as e:
        db.session.rollback()
        logger.error(f"Failed to create admin user: {e}")
        return jsonify({'error': f'Failed to create admin user: {e}'}), 500

    return jsonify({
        'success': True,
        'message': 'Setup complete! Gatekeeparr is ready.',
        'user': user.to_dict(),
        'env_path': ENV_FILE_PATH,
        'restart_note': 'A container restart is recommended to fully load the new configuration.',
    })


# ---------------------------------------------------------------------------
# Service test helpers
# ---------------------------------------------------------------------------

def _test_jellyseerr(url: str, api_key: str) -> dict:
    if not url or not api_key:
        return {'ok': False, 'error': 'URL and API key required'}
    try:
        from gatekeeper.services.jellyseerr import JellyseerrClient
        client = JellyseerrClient(url=url, api_key=api_key)
        ok = client.test_connection()
        return {'ok': ok, 'error': None if ok else 'Connection failed'}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


def _test_radarr(url: str, api_key: str) -> dict:
    if not url or not api_key:
        return {'ok': False, 'error': 'URL and API key required'}
    try:
        from gatekeeper.services.radarr import RadarrClient
        client = RadarrClient(url=url, api_key=api_key)
        ok = client.test_connection()
        return {'ok': ok, 'error': None if ok else 'Connection failed'}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


def _test_sonarr(url: str, api_key: str) -> dict:
    if not url or not api_key:
        return {'ok': False, 'error': 'URL and API key required'}
    try:
        from gatekeeper.services.sonarr import SonarrClient
        client = SonarrClient(url=url, api_key=api_key)
        ok = client.test_connection()
        return {'ok': ok, 'error': None if ok else 'Connection failed'}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


def _test_tmdb(api_key: str) -> dict:
    if not api_key:
        return {'ok': False, 'error': 'API key required'}
    try:
        import requests as req
        resp = req.get(
            'https://api.themoviedb.org/3/configuration',
            params={'api_key': api_key},
            timeout=10,
        )
        ok = resp.status_code == 200
        return {'ok': ok, 'error': None if ok else f'HTTP {resp.status_code}'}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


def _test_ai(provider: str, api_key: str, base_url: str, model: str) -> dict:
    if provider in ('claude', 'openai', 'grok') and not api_key:
        return {'ok': False, 'error': 'API key required for this provider'}
    if provider == 'ollama' and not base_url:
        return {'ok': False, 'error': 'Base URL required for Ollama'}

    try:
        if provider == 'claude':
            import requests as req
            resp = req.get(
                'https://api.anthropic.com/v1/models',
                headers={
                    'x-api-key': api_key,
                    'anthropic-version': '2023-06-01',
                },
                timeout=10,
            )
            ok = resp.status_code == 200
            return {'ok': ok, 'error': None if ok else f'HTTP {resp.status_code}'}

        elif provider == 'openai':
            import requests as req
            resp = req.get(
                'https://api.openai.com/v1/models',
                headers={'Authorization': f'Bearer {api_key}'},
                timeout=10,
            )
            ok = resp.status_code == 200
            return {'ok': ok, 'error': None if ok else f'HTTP {resp.status_code}'}

        elif provider == 'grok':
            import requests as req
            resp = req.get(
                'https://api.x.ai/v1/models',
                headers={'Authorization': f'Bearer {api_key}'},
                timeout=10,
            )
            ok = resp.status_code == 200
            return {'ok': ok, 'error': None if ok else f'HTTP {resp.status_code}'}

        elif provider == 'ollama':
            import requests as req
            resp = req.get(f'{base_url.rstrip("/")}/api/tags', timeout=10)
            ok = resp.status_code == 200
            return {'ok': ok, 'error': None if ok else f'HTTP {resp.status_code}'}

        return {'ok': False, 'error': f'Unknown provider: {provider}'}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


def _test_webhook(url: str, name: str) -> dict:
    if not url:
        return {'ok': False, 'error': 'Webhook URL required'}
    try:
        import requests as req
        # Just validate the URL is reachable; don't actually post
        resp = req.head(url, timeout=10, allow_redirects=True)
        # Mattermost webhooks return 405 for HEAD but that means the endpoint exists
        ok = resp.status_code in (200, 201, 204, 405)
        return {'ok': ok, 'error': None if ok else f'HTTP {resp.status_code}'}
    except Exception as e:
        return {'ok': False, 'error': str(e)}


def _apply_env_vars(data: dict):
    """Apply config values to current process environment."""
    mapping = {
        'jellyseerr_url': 'JELLYSEERR_URL',
        'jellyseerr_api_key': 'JELLYSEERR_API_KEY',
        'radarr_url': 'RADARR_URL',
        'radarr_api_key': 'RADARR_API_KEY',
        'sonarr_url': 'SONARR_URL',
        'sonarr_api_key': 'SONARR_API_KEY',
        'tmdb_api_key': 'TMDB_API_KEY',
        'ai_provider': 'AI_PROVIDER',
        'ai_api_key': 'AI_API_KEY',
        'ai_base_url': 'AI_BASE_URL',
        'ai_model': 'AI_MODEL',
        'mattermost_webhook': 'MATTERMOST_WEBHOOK',
        'discord_webhook': 'DISCORD_WEBHOOK',
    }
    for key, env_var in mapping.items():
        val = data.get(key)
        if val:
            os.environ[env_var] = str(val)

    # Reset the global config so it reloads from new env vars
    from gatekeeper.config import set_config
    set_config(None)
