#!/usr/bin/env bash
#
# Gatekeeper CLI Setup Wizard
#
# Interactive script that prompts for configuration and writes a .env file,
# then creates the initial admin user. Run from the host:
#
#   docker exec -it gatekeeper /app/scripts/setup.sh
#
# Or directly on the host (adjusting paths as needed):
#
#   ./scripts/setup.sh
#

set -euo pipefail

ENV_FILE="${GATEKEEPER_ENV_PATH:-/app/data/.env}"
DATA_DIR="$(dirname "$ENV_FILE")"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

prompt() {
    local var_name="$1"
    local label="$2"
    local default="${3:-}"
    local secret="${4:-}"

    if [ -n "$default" ]; then
        label="$label [$default]"
    fi

    if [ "$secret" = "secret" ]; then
        read -rsp "$label: " value
        echo
    else
        read -rp "$label: " value
    fi

    value="${value:-$default}"
    eval "$var_name=\"\$value\""
}

header() {
    echo
    echo "============================================"
    echo "  $1"
    echo "============================================"
    echo
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

echo
echo "  Gatekeeper - First Run Setup"
echo "  =============================="
echo

if [ -f "$ENV_FILE" ]; then
    echo "  An existing configuration was found at $ENV_FILE"
    read -rp "  Overwrite? [y/N]: " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "  Aborting."
        exit 0
    fi
fi

# -- Step 1: Jellyseerr --
header "Step 1: Jellyseerr"
prompt JELLYSEERR_URL "  Jellyseerr URL" "http://localhost:5055"
prompt JELLYSEERR_API_KEY "  Jellyseerr API Key" "" "secret"

# -- Step 2: Radarr --
header "Step 2: Radarr"
prompt RADARR_URL "  Radarr URL" "http://localhost:7878"
prompt RADARR_API_KEY "  Radarr API Key" "" "secret"

# -- Step 3: Sonarr --
header "Step 3: Sonarr"
prompt SONARR_URL "  Sonarr URL" "http://localhost:8989"
prompt SONARR_API_KEY "  Sonarr API Key" "" "secret"

# -- Step 4: TMDB --
header "Step 4: TMDB"
prompt TMDB_API_KEY "  TMDB API Key (v3)" "" "secret"

# -- Step 5: AI Provider --
header "Step 5: AI Provider"
echo "  Providers: claude, openai, grok, ollama"
prompt AI_PROVIDER "  Provider" "claude"
if [ "$AI_PROVIDER" = "ollama" ]; then
    prompt AI_BASE_URL "  Ollama Base URL" "http://localhost:11434"
    AI_API_KEY=""
else
    AI_BASE_URL=""
    prompt AI_API_KEY "  AI API Key" "" "secret"
fi
prompt AI_MODEL "  Model override (blank for default)" ""

# -- Step 6: Notifications (optional) --
header "Step 6: Notifications (optional)"
prompt MATTERMOST_WEBHOOK "  Mattermost Webhook URL (blank to skip)" ""
prompt DISCORD_WEBHOOK "  Discord Webhook URL (blank to skip)" ""

# -- Step 7: Admin user --
header "Step 7: Admin User"
prompt ADMIN_USERNAME "  Admin username" ""
prompt ADMIN_JELLYSEERR_USER "  Jellyseerr username for this admin" "$ADMIN_USERNAME"

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------

header "Writing configuration"

mkdir -p "$DATA_DIR"

cat > "$ENV_FILE" <<ENVEOF
# Gatekeeper configuration - generated by setup CLI
GATEKEEPER_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32)

# Jellyseerr
JELLYSEERR_URL=$JELLYSEERR_URL
JELLYSEERR_API_KEY=$JELLYSEERR_API_KEY

# Radarr
RADARR_URL=$RADARR_URL
RADARR_API_KEY=$RADARR_API_KEY

# Sonarr
SONARR_URL=$SONARR_URL
SONARR_API_KEY=$SONARR_API_KEY

# TMDB
TMDB_API_KEY=$TMDB_API_KEY

# AI Provider
AI_PROVIDER=$AI_PROVIDER
AI_API_KEY=$AI_API_KEY
ENVEOF

if [ -n "$AI_BASE_URL" ]; then
    echo "AI_BASE_URL=$AI_BASE_URL" >> "$ENV_FILE"
fi
if [ -n "$AI_MODEL" ]; then
    echo "AI_MODEL=$AI_MODEL" >> "$ENV_FILE"
fi

{
    echo ""
    echo "# Notifications"
    [ -n "$MATTERMOST_WEBHOOK" ] && echo "MATTERMOST_WEBHOOK=$MATTERMOST_WEBHOOK"
    [ -n "$DISCORD_WEBHOOK" ] && echo "DISCORD_WEBHOOK=$DISCORD_WEBHOOK"
} >> "$ENV_FILE"

echo "  Configuration written to $ENV_FILE"

# ---------------------------------------------------------------------------
# Create admin user via Python
# ---------------------------------------------------------------------------

header "Creating admin user"

python3 - "$ADMIN_USERNAME" "$ADMIN_JELLYSEERR_USER" <<'PYEOF'
import sys, os
sys.path.insert(0, '/app')
os.environ.setdefault('DATABASE_URL', 'sqlite:////app/data/gatekeeper.db')

# Load the new .env we just wrote
from dotenv import load_dotenv
load_dotenv(os.getenv('GATEKEEPER_ENV_PATH', '/app/data/.env'), override=True)

from gatekeeper.app import create_app
from gatekeeper.models import db, User

username = sys.argv[1]
js_username = sys.argv[2] if len(sys.argv) > 2 else username

app = create_app()
with app.app_context():
    existing = User.query.filter_by(username=username).first()
    if existing:
        print(f"  User '{username}' already exists (type: {existing.user_type})")
    else:
        user = User(
            username=username,
            user_type='admin',
            jellyseerr_username=js_username,
        )
        db.session.add(user)
        db.session.commit()
        print(f"  Admin user '{username}' created (jellyseerr: {js_username})")
PYEOF

echo
echo "  Setup complete!"
echo "  Restart the container to fully load the new configuration:"
echo "    docker compose up -d --force-recreate gatekeeper"
echo
